title: 'Grav MultiLang'
default_lang: en
author:
  name: 'John Appleseed'
  email: john@example.com
taxonomies:
  - tag
metadata:
  description: 'My Grav Site'
summary:
  enabled: false
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
